CREATE TABLE READER
(
	ID INT IDENTITY(1, 1) NOT NULL,
	DOCUMENT CHAR(11) NOT NULL,
	FIRST_NAME NVARCHAR(50) NOT NULL,
	LAST_NAME NVARCHAR(50) NOT NULL,
	STATUS BIT NOT NULL,
	CREATEDAT DATETIME2 NOT NULL,
	UPDATEDAT DATETIME2 NOT NULL,
	CONSTRAINT PK_READER PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT UK_READER UNIQUE (DOCUMENT)
)

CREATE TABLE BOOK
(
	ID INT IDENTITY(1, 1) NOT NULL,
	TITLE NVARCHAR(100) NOT NULL,
	AUTHOR NVARCHAR(50) NOT NULL,
	PAGES INT NOT NULL,
	PUBLISHER NVARCHAR(100) NOT NULL,
	ISBN_10 CHAR(10) NOT NULL,
	ISBN_13 CHAR(13) NOT NULL,
	LANGUAGE NVARCHAR(50) NOT NULL,
	CREATEDAT DATETIME2 NOT NULL,
	UPDATEDAT DATETIME2 NOT NULL,
	CONSTRAINT PK_BOOK PRIMARY KEY CLUSTERED (ID)
)


CREATE TABLE RENT_BOOK
(
	ID INT IDENTITY(1, 1) NOT NULL,
	READER_ID INT NOT NULL,
	BOOK_ID INT NOT NULL,
	RENTED BIT NOT NULL,
	RENTAL_DATE DATE NOT NULL,
	RETURN_DATE DATE NOT NULL,
	CREATEDAT DATETIME2 NOT NULL,
	UPDATEDAT DATETIME2 NOT NULL,
	CONSTRAINT PK_RENT_BOOK PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_RENT_BOOK_READER FOREIGN KEY (READER_ID) REFERENCES READER(ID),
	CONSTRAINT FK_RENT_BOOK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
)